name: test-report

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
  
    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc pull
          git fetch --prune

          echo "## Parameters (comparing with the master branch)" >> report.md          
          dvc params diff --all --show-md master >> report.md

          echo "## Metrics (comparing with the master branch)" >> report.md          
          dvc metrics diff --all --show-md master >> report.md

          echo "## Visualizations" >> report.md   
          cml publish resources/images/0.png --md >> report.md
          cml publish resources/images/1.png --md >> report.md
          cml publish resources/images/2.png --md >> report.md
          
          cml send-comment report.md 